<a href="https://colab.research.google.com/github/nilsberzins/stat-405-final/blob/main/EDA405.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Connect to Database and pull data

In [ ]:
!pip install pymysql
!pip install boto3
!pip install sqlalchemy
!pip install python-dotenv

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.8 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Collecting boto3
  Downloading boto3-1.38.30-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.39.0,>=1.38.30 (from boto3)
  Downloading botocore-1.38.30-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3)
  Downloading s3transfer-0.13.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from botocore<1.39.0,>=1.38.30->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<1.39.0,>=1.38.30->boto3) (2.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.39.0,>=1.38.30->boto3) (1.17.0)
Downloading boto3-1.38.30-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 3.1 MB/s eta 0:00:00
Downloading botocore-1.38.30-py3-none-any.whl (13.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 56.0 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.13.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 6.6 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.38.30 botocore-1.38.30 jmespath-1.0.1 s3transfer-0.13.0
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.41)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.2)
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

In [35]:
# package for env variables in google colab: https://pypi.org/project/colab-env/
!pip install colab-env -qU
import colab_env

In [34]:
from colab_env import envvar_handler # modify env variables in var.env file in google drive

In [33]:
import pymysql
import sys
import boto3
import os

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
connection = pymysql.connect(
    host=os.getenv("AWS_DATABASE_ENDPOINT"),
    user=os.getenv("AWS_USER"),
    port=int(os.getenv("AWS_PORT")),
    passwd=os.getenv("AWS_PASSWORD"),
    database=os.getenv("AWS_DBNAME")
)

In [32]:
with connection.cursor() as cursor:
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

2018_UC_salaries_data
2019_UC_salaries_data
2020_UC_salaries_data
2021_UC_salaries_data
2022_UC_salaries_data
2023_UC_salaries_data
CSU_salaries_data
SuperBowl_coinTosses
google_elev_68sites
iris_data
nhl_goalieDate
nhl_playerDate
nhl_teamDate

In [36]:
df2018 = pd.read_sql("SELECT * FROM 2018_UC_salaries_data", con=connection)

<ipython-input-36-63a79f0bfc87>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2018 = pd.read_sql("SELECT * FROM 2018_UC_salaries_data", con=connection)

In [ ]:
df2018.head()

,row_names,Year,EmployerType,EmployerName,DepartmentOrSubdivision,Position,ElectedOfficial,Judicial,OtherPositions,MinPositionSalary,...,HealthDentalVision,TotalRetirementAndHealthContribution,PensionFormula,EmployerURL,EmployerPopulation,LastUpdatedDate,EmployerCounty,SpecialDistrictActivities,IncludesUnfundedLiability,SpecialDistrictType
0,1,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,Tut-Gship,0,...,0,0,,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
1,2,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,Admissions Evaluator 3,0,...,18273,21546,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
2,3,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,6982,9323,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
3,4,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,403,403,N/A,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
4,5,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,9171,11800,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None

**EDA**

In [38]:
#ignore for now
years = range(2018, 2024)
dfs = []

for year in years:
    query = f"""
    SELECT '{year}' AS year, location, title, `regular.pay`
    FROM `{year}_UC_salaries_data`
    """
    df = pd.read_sql(query, con=connection)
    dfs.append(df)

full_data = pd.concat(dfs, ignore_index=True)
full_data.head()

<ipython-input-38-e3188a69c0eb>:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)

DatabaseError: Execution failed on sql '
    SELECT '2018' AS year, location, title, `regular.pay`
    FROM `2018_UC_salaries_data`
    ': (1054, "Unknown column 'location' in 'field list'")

In [ ]:
#ignore for now
df = pd.read_sql("SELECT * FROM `2018_UC_salaries_data` LIMIT 5;", con=connection)
df.head()

<ipython-input-8-5e27702b171f>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM `2018_UC_salaries_data` LIMIT 5;", con=connection)

,row_names,Year,EmployerType,EmployerName,DepartmentOrSubdivision,Position,ElectedOfficial,Judicial,OtherPositions,MinPositionSalary,...,HealthDentalVision,TotalRetirementAndHealthContribution,PensionFormula,EmployerURL,EmployerPopulation,LastUpdatedDate,EmployerCounty,SpecialDistrictActivities,IncludesUnfundedLiability,SpecialDistrictType
0,1,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,Tut-Gship,0,...,0,0,,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
1,2,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,Admissions Evaluator 3,0,...,18273,21546,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
2,3,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,6982,9323,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
3,4,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,403,403,N/A,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None
4,5,2018,University of California,"University of California, Berkeley",UC - Berkeley,Acad Achievement Cnslr 2,False,False,,0,...,9171,11800,2016 Tier,https://ucnet.universityofcalifornia.edu/compe...,None,09/24/2019,Alameda,None,False,None

In [47]:
#uploading locally
from google.colab import drive
import pandas as pd

# Step 1: Mount Google Drive
drive.mount('/content/drive')

# Step 2: Set base path
base_path = '/content/drive/MyDrive/UC_Salaries/'
years = range(2018, 2024)

# Step 3: Read and combine all CSVs
dfs = []

for year in years:
    file_path = f"{base_path}UCOP_Data_{year}.csv"
    try:
        df = pd.read_csv(file_path, on_bad_lines='skip', quotechar='"', delimiter=',')
        df['year'] = year
        dfs.append(df)
    except Exception as e:
        print(f"❌ Failed to read {file_path}: {e}")

full_data = pd.concat(dfs, ignore_index=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Combined dataset shape: (1891547, 10)

,id,year,location,first name,last name,title,gross pay,regular pay,overtime pay,other pay
0,1,2018,Merced,*****,*****,STDT 1,2442.0,2442.0,0.0,0.0
1,2,2018,Riverside,*****,*****,STDT 1,1929.0,1859.0,0.0,70.0
2,3,2018,San Diego,*****,*****,STDT 2,633.0,633.0,0.0,0.0
3,4,2018,San Diego,*****,*****,TEACHG ASST-GSHIP,23082.0,22982.0,0.0,100.0
4,5,2018,San Diego,*****,*****,TUT-GSHIP,1833.0,1833.0,0.0,0.0

In [49]:
full_data = full_data[["year", "location", "title", "regular pay"]]
full_data.head()

   year   location              title  regular pay
0  2018     Merced             STDT 1       2442.0
1  2018  Riverside             STDT 1       1859.0
2  2018  San Diego             STDT 2        633.0
3  2018  San Diego  TEACHG ASST-GSHIP      22982.0
4  2018  San Diego          TUT-GSHIP       1833.0

In [50]:
full_data = full_data.dropna()

In [51]:
to_drop = ["San Francisco", "UCOP", "DANR", "Hastings", "Hastings College of Law"]
full_data = full_data[~full_data["location"].isin(to_drop)]

In [57]:
pattern = r"""(?ix)                     # (?i)=ignore-case  (?x)=verbose mode
    \b(?:                               # word-start, then one of…
        prof(?:essors?\b|\.?\b)         #  "professor" / "professors" / "prof" / "prof."
      | lect(?:urer?s?\b|\b)            #  "lecturer(s)" / "lect"
    )
"""

filtered = full_data[full_data['title'].str.contains(pattern, regex=True, na=False)]

      year  location                   title  regular pay
14    2018  Berkeley  LECT IN SUMMER SESSION        925.0
175   2018  Berkeley  LECT IN SUMMER SESSION      12609.0
1359  2018  Berkeley  LECT IN SUMMER SESSION      12391.0
1478  2018  Berkeley  LECT IN SUMMER SESSION        733.0
1714  2018  Berkeley                 LECT-FY      13721.0

In [59]:
filtered = filtered[~(filtered["title"].str.contains("SUMMER"))]

In [ ]:
filtered.head()

     year    location                        title  regular.pay
0    2010  Santa Cruz  ASSISTANT PROFESSOR-ACAD YR     69999.96
20   2010    Berkeley     LECTURER - ACADEMIC YEAR     25454.75
94   2010    Berkeley     LECTURER - ACADEMIC YEAR     29248.46
175  2010    Berkeley     LECTURER - ACADEMIC YEAR     27058.69
178  2010    Berkeley     LECTURER - ACADEMIC YEAR     28679.78

In [60]:
def title_assign(x):
    if "PROFL" in x or "PROFESSIONAL" in x:
        return "OTHER"
    elif "VST" in x and "ASST" in x:
        return "VST ASST"
    elif "VST" in x and "ASSOC" in x:
        return "VST ASSOC"
    elif "VST" in x:
        return "VST PROF"
    elif "ADJ" in x and "ASST" in x:
        return "ADJ ASST"
    elif ("ASOC" in x or "ASSOC" in x) and "ADJ" in x:
        return "ADJ ASOC"
    elif "ADJ" in x:
        return "ADJ PROF"
    elif ("ASST" in x or "ASSIST" in x) and "PROF" in x:
        return "ASST PROF"
    elif "ASSOC" in x and "PROF" in x:
        return "ASSOC PROF"
    elif "PROF" in x:
        return "PROF"
    elif "SR" in x and "LECT" in x:
        return "SR LECT"
    elif "LECT" in x:
        return "LECT"
    else:
        return "OTHER"

In [61]:
filtered['prof_rank'] = (
    filtered['title']
        .str.upper()
        .fillna('')
        .apply(title_assign)
)

filtered.head()

      year  location         title  regular pay prof_rank
1714  2018  Berkeley       LECT-FY      13721.0      LECT
1741  2018  Berkeley  LECT-AY-1/10      15384.0      LECT
2580  2018  Berkeley       LECT-FY       9373.0      LECT
2584  2018  Berkeley  LECT-AY-1/10      15216.0      LECT
4864  2018  Berkeley  LECT-AY-1/10       5513.0      LECT

In [64]:
avg_salary = (
    filtered
      .groupby(['prof_rank', 'location'], as_index=False)
      .agg(avg_regular_pay=('regular pay', 'mean'))
)

avg_salary

    prof_rank     location  avg_regular_pay
0    ADJ ASOC     Berkeley     84046.198473
1    ADJ ASOC        Davis     89792.720000
2    ADJ ASOC       Irvine     78764.080645
3    ADJ ASOC  Los Angeles     94256.959144
4    ADJ ASOC    Riverside     78513.148148
..        ...          ...              ...
77  VST ASSOC   Santa Cruz         0.000000
78   VST ASST        Davis      4096.000000
79   VST PROF        Davis      3333.000000
80   VST PROF  Los Angeles      2360.000000
81   VST PROF   Santa Cruz         0.000000

[82 rows x 3 columns]